### PR TITLE
Switch to Python 3 & Add tests

### PR DESCRIPTION
**Pull request by sebastic**
These changes implement the switch to Python 3 and add tests with pytest and its coverage plugin.

The initial changes fix all issues reported by flake8 to make the code adhere to PEP3 and catch obvious issues with Python 3, these changes are prefixed with `flake8:`.

The Python 3 related changes follow and are prefixed with `python3:`.

While testing the Python 3 changes some bugs were found and fixed, these changes are prefixed with `bug:`.

The final changes add tests using the pytest framework. The `pytest.sh` scripts executes pytest for the unit tests, flake8 for the PEP8 code style, and codespell to catch spelling errors. If any of these fail the scripts exits with a non-zero status.

The pytest coverage plugin currently reports 100% coverage, this was only possible by skipping a few statements (by marking them with `# pragma` comments) that cannot be tested easily. This includes the `__main__` code in `autorsyncbackup.py` for example.

The `config` and `logger` singleton classes complicate testing somewhat, all tests that use the `config` class should use the `test_config` fixture to ensure that the first test that instantiates the class configures it appropriately for tests.

The rsync, ssh, and mailer methods are monkeypatched to not need network access, the responses are mocked for rsync & ssh, and for the mailer send method the email is written to a file instead.

The director `getBackupsSize` & jobrunhistory `identifyJob` tests are a bit flaky, they sometimes fail likely due to a race condition. These tests have been marked accordingly, a more permanent solution is still needed.

While there are many changes, the individual commits should be easy to review.

Note: Due not having Travis enabled for my fork, the config could not be tested before hand, this PR will be rebased if it needs further changes.

Fixes: #47

### CODE REVIEW

**Comment by teunis90** [comment]
@sebastic I've merged your PR, updates our servers too and activated Travis-CI:

https://travis-ci.com/Nextpertise/autorsyncbackup/jobs/277307464

Can you have a look at the errors? Looks like all/most of them have something todo with `fixture 'tmp_path' not found`.

**Comment by sebastic** [comment]
`tmp_path` was added in pytest 3.9.0, Debian buster has 3.10.1, but Ubuntu bionic has 3.3.2 which only provides the `tmpdir` fixture.

The tests in question can be marked with `skipIf` to ensure they're only executed with a recent enough pytest, or change them all to use `tmpdir`. I'm leaning towards the former.

**Comment by teunis90** [comment]
If I understand it correctly, this would be fixed if we switch to `Buster` on Travis?

Also, I see that we recommend to install Deb packages over Pip packages. If we would move to Pip packages we can add a `requirements.txt` which would make the installation process easier.

**Comment by sebastic** [comment]
If Travis supported Debian that would be an option, but it only provides Ubuntu environment, switching to focal (the next LTS) when Travis adds support for it is an option.

To get a Debian environment you need to use Docker.

Converting the project to a proper Python distribution with setuptools is good idea, that needs some restructuring of the codebase though.

Using pip to install more recent versions of dependencies than those included in bionic is a good option too, and likely the least amount of work.

**Comment by sebastic** [comment]
#49 fixes the Travis failures by installing the same version of pytest & pytest-cov as included in Debian buster with pip3.

**Comment by teunis90** [comment]
For our other Travis project we do use Docker, wasn't aware that it is Ubuntu only.
Thanks for your efforts to make Travis happy :)

**Comment by sebastic** [comment]
You're welcome.

I've switched our Jenkins job to use the master branch from this repo instead the python3 branch from my fork as a second opinion, it uses a buster cowbuilder chroot to run the tests.

**Comment by teunis90** [comment]
@ovi82 said something about the Jenkins environment you've set up. That's super!

**Pull request merged**
